Feat/014 design system draft
YAPP-Github/21st-Web-Team-2-FE pull request #24
Opened 2022-12-05 15:32 UTC by Kimsj912

close #ISSUE_NUMBE

## 💡 개요
![image](https://user-images.githubusercontent.com/48820696/205676592-90a528e5-c947-494d-b699-2a99e1f12bf1.png)

## 📝 작업 내용
1. theme파일(color, fontWeight, fontSize 등을 관리) 생성
2. Example 컴포넌트( 스타일 파일, 컴포넌트 파일, index파일, 스토리북파일) 세트 생성

## ‼️ 주의 사항
- Example 컴포넌트는 예시용이기 때문에 추후에 삭제가 필요합니다.
- GlobalStyle로 관리하기보다는 reset.css가 더 간결하고 깔끔하게 관리될 것 같아 reset.css로 관리하게 변경하였습니다. 의견있으시면 언제든지 코멘트 남겨주세요

## 🔗 참고자료

2022-12-06 09:43 UTC, hwookim requested changes
고생하셨습니다! 😄 
몇가지 코멘트 남겨뒀으니 확인 부탁드려요~~

2022-12-06 09:43 UTC, hwookim commented on .eslintrc.js
> +    '@typescript-eslint/ban-ts-comment': 'off',
해당 옵션을 적용해야할 일이 있을까요?
`// @ts-ignore`같은 주석을 허용하는 건데, 지금 상태에서 필요해보이진 않습니다. [참고](https://typescript-eslint.io/rules/ban-ts-comment/)
추후에도 필요할 것 같다는 생각이 들진 않네요 🤔

2022-12-06 09:43 UTC, hwookim commented on src/styles/theme.ts
> +    small: '12px',
얘만 sm이 아닌 이유가 있을까요 👀

2022-12-06 09:43 UTC, hwookim commented on src/styles/theme.ts
> +    borderPrimary: '#666666',
혹시 현재의 디자인시스템은 어떤 걸 기준으로 한걸까요?
피그마에 등록된 색상표와 폰트표가 있긴 한데, 이를 기준으로 하는 건 어떨까 싶습니다!

![스크린샷 2022-12-06 18 08 31](https://user-images.githubusercontent.com/45786387/205868433-120ecd0d-c7df-4471-bf76-380a218cc6a0.png)

2022-12-06 10:04 UTC, Kimsj912 commented on .eslintrc.js
> +    '@typescript-eslint/ban-ts-comment': 'off',
데브캠때 ts 관련 오류 때문에 넣었었는데 코드 수정 뒤 다시 확인해보니 안뜨네요! 좋은 피드백 감사합니당:)

2022-12-06 10:05 UTC, Kimsj912 commented on src/styles/theme.ts
> +    small: '12px',
엇 이런게 있었네요?! 수정했습니다 !!

2022-12-06 10:06 UTC, Kimsj912 commented on src/styles/theme.ts
> +    borderPrimary: '#666666',
혜진님이 디자인을 바꿔오신다고하셔서 기본적으로 이름만 primary, secondary 쓰는걸 PR 리뷰로 확인받으며 넌지시 제안해보고자 작성을 했습니다. 이번엔 theme.ts 연결이나 사용법등을 공유하고 다음에 디자인나오면 이에 맞춰서 색 변경해보도록 하겠습니다!

2022-12-07 01:45 UTC, hwookim commented on src/styles/theme.ts
> +    borderPrimary: '#666666',
아하 그런 의도였군여!
그러면 추후 디자인 나오면 변경하는 걸로 하고 일단은 이대로 둬도 좋을 것 같네요 👍🏼

2022-12-07 01:46 UTC, hwookim approved these changes
머지하기 전에 `Exmple` 컴포넌트가 `_app.page.tsx`에만 안남도록 해주시면 감사하겠습니다!

2022-12-07 14:27 UTC, Kimsj912 commented
> 

넵 제거해서 올려뒀습니다!! 확인해주시고 approve 눌러주세용!

2022-12-07 18:29 UTC, KIMSEUNGGYU reviewed
수고하셨습니다~~

2022-12-07 18:29 UTC, KIMSEUNGGYU commented on src/components/Example/Example.style.tsx
> +import theme from '../../styles/theme';
이 친구도 나중에 path-alias 로 적용하면 좋을거 같아요!

2022-12-07 18:29 UTC, KIMSEUNGGYU commented on src/components/Example/Example.tsx
> +const MyButton = ({ title, ...props }: IMyButton) => {
여기서 ...props 로 가져왔는데 어디서 사용할 예정이신가요??

2022-12-07 18:29 UTC, KIMSEUNGGYU approved these changes

2022-12-09 12:39 UTC, Kimsj912 commented on src/components/Example/Example.style.tsx
> +import theme from '../../styles/theme';
좋아욥!! 지금 혹시 적용시킬 수 있을까요?

2022-12-09 12:40 UTC, Kimsj912 commented on src/components/Example/Example.tsx
> +const MyButton = ({ title, ...props }: IMyButton) => {
예시라 가져오긴 했는데 사용하는걸 잊어버렸네요...! 다음에 노트북 제대로 켰을 떄 반영 수정하도록 하겠습니다 !!

2022-12-25 16:04 UTC, Kimsj912 commented
![image](https://user-images.githubusercontent.com/48820696/209474815-8f9d37e5-5f3f-4fd8-8078-306cc2800767.png)
![image](https://user-images.githubusercontent.com/48820696/209474818-881c2510-a04a-4e4c-9f3b-db8fdb9092cf.png)

2022-12-26 기준으로 피그마에 올라와 있는 디자인 특징들 다시 추가해서 올렸습니다 👍

2022-12-26 01:00 UTC, hwookim requested changes
크리스마스였는데도,,, 고생하셨습니다 수정님! 😭
몇가지 리뷰 남겼으니 확인 부탁드립니다!

2022-12-26 01:00 UTC, hwookim commented on src/styles/reset.css
> +
해당 내용은 `reset.css`와는 다른 내용이니 별도의 `global.css`이나 `common.css`로 관리하는 건 어떨까 싶습니다!
만약 분리하게 된다면 해당 파일도 `.storybook/preview.js`에 추가해주시면 좋을 것 같아요!

아래의 body, h1 등의 내용도 포함해서요 😄

2022-12-26 01:00 UTC, hwookim commented on src/styles/theme.ts
> +const theme = {
되도록이면 혜진님께서 피그마에서 사용 중이신 이름과 맞췄으면 합니다!
다른 이름을 가지고 있다면 결국 매번 확인해야하는 번거로움이 생길 것 같아요.
<img width="133" alt="스크린샷 2022-12-26 09 53 12" src="https://user-images.githubusercontent.com/45786387/209486777-e626fc6d-fdeb-491c-a36c-a28143add9fb.png">

2022-12-26 01:00 UTC, hwookim commented on src/styles/theme.ts
> +    lg: '16px', // hashtag
`md`보다 `lg`가 더 작네요?? 👀 

`Select button`의 경우에는 `8px`이기도 하고, `Toggle button`은 `100px`이고...
이 경우에는 관리하기 보다는 각각 파일에서 지정해주는 게 더 효율적일 것 같다는 생각이 듭니다!

2022-12-26 01:00 UTC, hwookim commented on src/components/Example/Example.tsx
> +    </div>
어차피 예시긴 하지만,,
div로 감쌀 의미가 있을까요? 🤔

2022-12-26 04:36 UTC, KIMSEUNGGYU commented on src/styles/theme.ts
> +const theme = {
저도 동의합니다!

2022-12-26 04:42 UTC, KIMSEUNGGYU reviewed
고생하셨습니다~ 👍👏 
저도 몇가지 리뷰 남겼습니다. 
홧팅!

2022-12-26 04:42 UTC, KIMSEUNGGYU commented on src/components/Example/Example.style.tsx
> +import theme from '../../styles/theme';
theme 를 제대로 적용했으면 props 로 theme 를 가져와야 하는데 지금은 theme 를 import 하는 구조인 거 같아요!
한번 확인해주세요!! 
- themeProvider 로 감싸서 처리하는거 같아요

https://emotion.sh/docs/theming

2022-12-26 04:42 UTC, KIMSEUNGGYU commented on src/components/Example/Example.tsx
> +interface IMyButton {
저 같은 경우 컴포넌트에 필요한 props 에 타입인 경우 `Props` 또는 `MyButtonProps` 와 같이 처리하는 편인데 어떠신가요??

2022-12-26 04:42 UTC, KIMSEUNGGYU commented on src/styles/theme.ts
> +    lg: '16px', // hashtag
스토리북에 Color 하고 fontSize 별 typography 스토리북도 있으면 좋을거 같아요! (너무 바쁘시면 추후에 도입해도 괜찮을거 같긴합니다, 제가 해도 괜찮구요!)

[참고]
- https://storybook.js.org/docs/react/writing-docs/doc-block-colorpalette

2022-12-26 05:12 UTC, hwookim commented on src/components/Example/Example.style.tsx
> +import theme from '../../styles/theme';
아직까진 동적 테마를 사용하지 않기 때문에 상관은 없긴 할텐데,
만약 다크모드같은게 별도로 개발된다면 필요할지도 모르겠습니다.
다만 우리 사이트는 기본적으로 어두운 색 베이스고 디자이너도 고려하지 않기 때문에 필수적으로 적용할 필요는 없어보이긴 하네요 👀 

stackoverflow에도 [비슷한 논의](https://stackoverflow.com/questions/69620603/what-are-the-advantages-of-using-themeprovider-vs-importing-the-theme-directly-i)가 하나 있네요.

말씀하신 방법은 props로 접근해야하기 때문에 조금 더 길어진다는 단점이 생기긴 합니다.
저는 import 방식도 충분히 괜찮다고 생각해요!

2022-12-26 05:13 UTC, hwookim commented on src/components/Example/Example.tsx
> +interface IMyButton {
저도 I 태그를 쓰는 것보단 Props에 한표 던지겠습니다!

2022-12-31 21:53 UTC, Kimsj912 commented on src/styles/reset.css
> +
넵 좋아요오! 그렇게 반영하도록 하겠습니다 :)

2023-01-01 06:09 UTC, Kimsj912 commented on src/styles/theme.ts
> +const theme = {
말씀하신대로 color와 textsize borderRadius 변경완료하였습니다!!

2023-01-01 06:12 UTC, Kimsj912 commented on src/components/Example/Example.tsx
> +    </div>
ㅋㅋㅋㅋ 그러네요! <></>로 수정하겠습니다

2023-01-01 06:13 UTC, Kimsj912 commented on src/components/Example/Example.style.tsx
> +import theme from '../../styles/theme';
저도 themeProvider가 나쁘진 않지만 import방식이 현재에는 좀 더 편리한것 같아요

2023-01-01 06:41 UTC, Kimsj912 commented
머지까지 완료했습니다! 다들 한번씩 확인해주세요 @KIMSEUNGGYU  @hwookim

2023-01-01 06:47 UTC, hwookim commented on src/components/Example/Example.tsx
> +    </div>
아예 아무것도 감싸지 않는 편이 좋을 것 같습니다!

2023-01-01 07:40 UTC, hwookim requested changes
크리스마스에 새해까지 고생하십니다 수정님!

2023-01-01 07:40 UTC, hwookim commented on .storybook/preview.js
> +import '../src/styles/common.css';
👍🏼

2023-01-01 07:40 UTC, hwookim commented on src/pages/_app.page.tsx
> +function MyApp({ Component, pageProps }: AppProps) {
`_app.page.tsx`도 있고 `_app.tsx`도 있네요.
app이 page는 아니니 후자가 더 맞는 것 같고요! 👀 
아마 충돌 해결하다가 생긴 결과 같습니다!

2023-01-01 07:40 UTC, hwookim commented on src/pages/_app.page.tsx
> +import '../styles/reset.css';
```suggestion
import '../styles/reset.css';
import '../styles/common.css';
```

reset보다는 common이 우선적으로 적용되어야하니 순서를 바꿔야할 것 같습니다!

2023-01-01 07:40 UTC, hwookim commented on src/components/Example/Example.style.tsx
> +import theme from '../../styles/theme';
머지 작업을 거치셨다면 지금 적용시키실 수 있어요!

2023-01-01 07:40 UTC, hwookim commented on src/styles/theme.ts
> +    lg: '100px', // hashtag
이전 리뷰에도 남겼다싶이,
컴포넌트마다 너무 다양해서 이걸 시스템적으로 가져가는 게 의미가 있을지 모르겠습니다.
몇개만 훑어봐도 8px(side-menu), 4px(Badge) 짜리가 보이는데 같은 속성의 어떤건 관리대상이고 어떤건 관리대상이 아니면 더 혼란만 야기할 것 같아요.
`border-radius`는 관리 대상에서 제외시키는 편이 나을 것 같습니다!

2023-01-01 09:23 UTC, hwookim commented on src/pages/_app.tsx
> +import '@/styles/reset.css';
import 문 관련 prettier 때문에 무조건 common이 앞에 오게 되는군요... 😢
일단 현재는 이렇게 작업하고 추후 import관련 prettier를 제거하거나 해야겠네요....
@KIMSEUNGGYU 혹시 방법 아실까요?

2023-01-01 09:33 UTC, hwookim commented on src/pages/_app.tsx
> +import '@/styles/reset.css';
[관련 PR](https://github.com/trivago/prettier-plugin-sort-imports/pull/42)이 한 번 머지된 적이 있었네요.

`.prettierrc.js`의 `importOrder`부분을 수정하면 대응할 수 있어보입니다.
```js
  importOrder: ['^@mocks/(.*)$', '@src/styles/reset.css', '@src/styles/common.css', '^@src/(.*)$', '^[./]'],
```
다만 이렇게하면 한 줄 공백이 생기긴 하네요... 🤔

2023-01-01 10:34 UTC, KIMSEUNGGYU approved these changes
연말 및 새해 동안 고생하셨습니다!!!  👍

2023-01-01 10:34 UTC, KIMSEUNGGYU commented on src/pages/_app.tsx
> +import '@/styles/reset.css';
맞아요ㅠㅠ import 순서 규칙을 통해 해결할 수 있지만, 그러면 공백이 생겨서.. importOrder prettier 를 제거하는것도 괜찮을수도 있겠네요 ㅎㅎ

2023-01-01 10:34 UTC, KIMSEUNGGYU commented on src/styles/theme.ts
> +const theme = {
와우!! 너무 좋아졌네요!! 굿굿굿!! 👍👍

2023-01-01 11:25 UTC, Kimsj912 commented
지금까지 피드백 반영하여 커밋 올렸습니다!!  @KIMSEUNGGYU @hwookim 
![image](https://user-images.githubusercontent.com/48820696/210168905-50276b54-7a9f-4739-bdb8-b67677a0cee2.png)

2023-01-01 14:19 UTC, hwookim approved these changes
마지막으로 하나만 확인해주시면 감사하겠습니다.
고생 많으셨습니다 수정님! 😢

2023-01-01 14:19 UTC, hwookim commented on src/pages/_app.page.tsx
> +import 'src/styles/reset.css';
여전히 common보단 reset이 우선순위로 되겠네요.
이전 리뷰 확인해서 적용해주시고 그 뒤에 머지해주세요.

2023-01-01 14:25 UTC, merged