[feat] Header UI 구현
YAPP-Github/21st-Web-Team-2-FE pull request #25
Opened 2022-12-07 18:40 UTC by KIMSEUNGGYU

close #17 

## 💡 개요
- header UI 구현
![image](https://user-images.githubusercontent.com/45627868/206267763-68902285-808e-4d5a-a736-db51b31545b2.png)

## 📝 작업 내용
- [x] 헤더 UI 구현 및 스토리 작성 및 (렌더) 테스트 코드 작성

## ‼️ 주의 사항
- 디자인이 다 나오지 않고 적용한 거라서 디자인이 다 나온 다음에 merge 해도 괜찮다고 생각합니다~~ \

## 🔗 참고자료

2022-12-08 04:44 UTC, hwookim requested changes
고생하셨습니다 승규님!
몇가지 리뷰 달아뒀으니 확인 부탁드려요ㅎㅎ

2022-12-08 04:44 UTC, hwookim commented on src/components/Header/Header.tsx
> +const HeaderWrapper = styled.header`
style 파일은 분리해서 관리하기로 한 거 아니었나요?

2022-12-08 04:44 UTC, hwookim commented on src/components/Header/Header.tsx
> +      <div className="content">
styled-component 방식을 쓰면서도 className을 쓰시는 이유가 있을까요?
관리 방식이 두가지가 혼합되는 상황은 좋지 않은 것 같아요.

제가 느끼는 styled-component 방식의 큰 장점 중 하나가 IDE 내에서 Link 방식을 통해 바로 찾아갈 수 있게 해준다는 것인데,
이런 방식을 이용하게 된다면 `content`에 대한 스타일을 수정하고 싶을 때 바로 찾아가기 힘들지는 않을까요?

2022-12-08 04:44 UTC, hwookim commented on src/pages/Home.test.tsx
> +    expect(login).toBeInTheDocument();
헤더에서 진행되는 테스트를 모두 할 필요가 있을까요?
헤더가 있는지 정도만 봐도 괜찮다고 생각합니다.

하위의 테스트를 상위에서 모두 할 필요도 없고 하면 안된다고 생각합니다.
나중에 가면 상위 컴포넌트들은 파일이 엄청 비대해지고, 중복되는 테스트로 인해 테스트 작업에 소요도 오래 걸릴 것 같아요.

2022-12-08 04:44 UTC, hwookim commented on src/pages/Home.test.tsx
> +    expect(searchImage).toBeInTheDocument();
위에와 테스트 내용이 겹치네요.
헤더의 책임인 것 같기도 하고요.

2022-12-08 04:44 UTC, hwookim commented on src/pages/_app.page.tsx
> +import '../styles/common.css';
storybook에도 적용되면 좋을 것 같습니다!

2023-01-04 14:13 UTC, KIMSEUNGGYU commented
디자인 시스템 및 아이콘 을 추가한 상태의 develop 브랜치에서 다시 재 작업하여 PR 요청 보냅니다!! 

Header 컴포넌트는 저희 서비스에 항상 보여서 우선은 `app.tsx` 에 Header 컴포넌트를 추가하였는데 괜찮은지 봐주시면 좋을거 같아요!!

2023-01-05 12:51 UTC, hwookim approved these changes
고생하셨습니다 👍🏼 👍🏼

2023-01-05 12:51 UTC, hwookim commented on src/components/Header/Header.tsx
> +        <S.LogoIcon name="Logo" width="189px" height="35px" />
로고에 메인으로 가는 링크정도는 있어도 괜찮다는 생각이 드네용

2023-01-05 13:02 UTC, KIMSEUNGGYU commented on src/components/Header/Header.tsx
> +        <S.LogoIcon name="Logo" width="189px" height="35px" />
아 저도 그 부분 고민했는데 아직 페이지가 제대로 나오지 않은거 같아서 추가 안했는데 그냥 추가해도 괜찮을거 같아서 추가해놓겠습니다.

2023-01-05 14:11 UTC, merged