[feat] 아이콘 컴포넌트 구현 (SVG ICON)
YAPP-Github/21st-Web-Team-2-FE pull request #28
Opened 2023-01-02 14:18 UTC by KIMSEUNGGYU

close #26 

## 💡 개요
![image](https://user-images.githubusercontent.com/45627868/210237054-cee10a2e-7f6f-49cd-b9a6-2c17d948bb95.png)
- SVG 기반 Icon 컴포넌트 구현

## 📝 작업 내용
- [x] 현재 디자인에서 사용하는 SVG 파일 등록하기
- [x]  SVG 파일을 사용할 수 있는 ICON 컴포넌트 구현하기

## ‼️ 주의 사항
- svg 가 fill 로 스타일 적용하는 것도있고, stroke 로 하는 것도 있고, 하나의 svg 안에 여러 개의 fill로 있는 것도있어서 컬러 변경이 애매함.
- 하지만 현재는 stroke 속성으로 색 변경으로 충분하기에 해당 속성을 Icon 컬러를 제어했으며, 추후에 fill 등 SVG 형태를 통일성있게 관리해야함!

## 🔗 참고자료
- [nextjs, storybook svg 설정](https://github.com/storybookjs/storybook/issues/18557)

2023-01-02 16:18 UTC, hwookim commented
현재 수정님의 이전 커밋들이 모두 올라와있는 상태라서, 한 번 확인해보시고 다시 작업하셔야할 것 같습니다!

추천드리는 방법으로는 `git pull --rebase origin develop`를 통해서 현재 develop 위로 커밋의 시작점을 변경하는 방법이 있습니다.
충돌 해결하신 뒤에 force push하시면 커밋이 정리될 것 같습니다.

2023-01-03 01:34 UTC, hwookim requested changes
고생하셨습니다 승규님!
리베이스 및 리뷰 확인 부탁드립니다!

2023-01-03 01:34 UTC, hwookim commented on src/assets/icon.tsx
> +export { ReactComponent as HandsUp } from './emoji_hands up.svg';
```suggestion
export { ReactComponent as HandsUp } from './emoji_hands_up.svg';
```

띄워쓰기 있어도 괜찮나요? 
사실 실행에는 상관 없긴 한데 그냥 제 눈에 보여버렸습니다 ㅋㅋ

2023-01-03 01:34 UTC, hwookim commented on src/components/common/Icon/Icon.tsx
> +import theme from '../../../styles/theme';
alias를 쓰면 더 좋을 것 같습니다!

2023-01-03 01:34 UTC, hwookim commented on src/assets/icon.tsx
> +export { ReactComponent as Carrer } from './emoji_career.svg';
```suggestion
export { ReactComponent as Career } from './emoji_career.svg';
```
오타가 있습니다!

2023-01-03 01:34 UTC, hwookim commented on src/components/common/Icon/Icon.tsx
> +type Color = keyof typeof theme.color;
각 파일에서 export해도 괜찮지 않을까요?

2023-01-03 01:34 UTC, hwookim commented on src/components/common/Icon/Icon.tsx
> +import * as icon from '../../../assets/icon';
asset 안에서 icon으로 폴더 구조를 한 번 묶어야하지 않을까 싶습니다!
추후 이미지같은 게 추가된다면 헷갈릴 수도 있을 것 같아요.
그렇다면 icon.tsx를 index.tsx로 바꿔도 될지도요?

2023-01-03 01:34 UTC, hwookim commented on src/pages/_app.page.tsx
> +import 'src/styles/reset.css';
커밋 정리하시면 이 파일은 삭제되겠네요 👀

2023-01-03 01:34 UTC, hwookim commented on .gitignore
> +# Icon
그냥 사소한 궁금증인데,, 🤔 
왜 Icon에 대해서 ignore가 진행되고 있었을까요??

찾아봤는데 마땅한 이유가 보이지는 않네요.. 궁금쓰,,

2023-01-03 07:43 UTC, KIMSEUNGGYU commented on src/assets/icon.tsx
> +export { ReactComponent as HandsUp } from './emoji_hands up.svg';
오 띄어쓰기가 있었군요! 수정하겠습니다
굿굿굿

2023-01-03 07:46 UTC, KIMSEUNGGYU commented on src/components/common/Icon/Icon.tsx
> +type Color = keyof typeof theme.color;
각 파일에서 export 한다는 정확한 의미를 모르겠어요ㅠㅠ 
좀 더 상세하게 설명 부탁드립니다.

2023-01-03 07:49 UTC, KIMSEUNGGYU commented on .gitignore
> +# Icon
그러니깐요 ㅋㅋㅋ 저도 이 부분이 있어서.. 왜 있지?? ㅋㅋㅋㅋ 고민해봤는데 모르겠더라구요!

2023-01-03 08:37 UTC, hwookim commented on src/components/common/Icon/Icon.tsx
> +type Color = keyof typeof theme.color;
Icon 내부에서 각 타입을 선언하는 것보다는
theme 파일 내에서 Color 등의 각 타입을 선언하고 해당 타입을 import해서 사용하는 편이 어떨까 싶어서 남긴 리뷰였습니다!
Color 타입이 Icon에 종속된 내용은 아니니까요.

IconNameType은 조금 결이 다르긴 하지만요... 🤔

2023-01-03 09:49 UTC, KIMSEUNGGYU commented on src/components/common/Icon/Icon.tsx
> +type Color = keyof typeof theme.color;
음.. 이부분은 말씀했다시피 결이 조금 달라서, 우선 Icon 에서만 IconName 이 필요할거 같습니다! 
그래서 해당 부분은 변경하지 않았습니다.

2023-01-03 10:18 UTC, hwookim commented on src/components/common/Icon/Icon.tsx
> +type Color = keyof typeof theme.color;
그렇다면 Color 부분은 어떻게 생각하시는 걸까요?
제가 주로 말한건 Color 인걸요 😢

2023-01-03 10:39 UTC, KIMSEUNGGYU commented on src/components/common/Icon/Icon.tsx
> +type Color = keyof typeof theme.color;
아하!! 컬러는 theme 에서 관리해도 괜찮을거 같아요

2023-01-03 12:07 UTC, hwookim approved these changes
고생하셨습니다 👍🏼

2023-01-04 04:29 UTC, merged